-- Register the supplied product photos in inventory as unpublished placeholders.
-- Names, prices, and stock can be edited from the staff inventory screen before publishing.

INSERT OR IGNORE INTO products (category_id, name, slug, description, price, stock, image_key, is_active, metadata_json)
VALUES ((SELECT id FROM categories WHERE slug = '伴手禮'), '伴手禮新品圖片 01', 'new-souvenir-image-01', '待補商品名稱、價格與規格，先建立圖片庫存資料。', 0, 0, 'images/S__293707786.jpg', 0, '{"priceValue":0,"day":5,"img":"/assets/images/S__293707786.jpg","desc":"待補商品名稱、價格與規格，先建立圖片庫存資料。","sku":"new-souvenir-image-01","temporaryPrice":true,"newArrival":true}');
INSERT OR IGNORE INTO product_images (product_id, image_key, sort_order, is_primary) SELECT id, 'images/S__293707786.jpg', 0, 1 FROM products WHERE slug = 'new-souvenir-image-01';
INSERT OR IGNORE INTO products (category_id, name, slug, description, price, stock, image_key, is_active, metadata_json)
VALUES ((SELECT id FROM categories WHERE slug = '伴手禮'), '伴手禮新品圖片 02', 'new-souvenir-image-02', '待補商品名稱、價格與規格，先建立圖片庫存資料。', 0, 0, 'images/S__294150148_0.jpg', 0, '{"priceValue":0,"day":5,"img":"/assets/images/S__294150148_0.jpg","desc":"待補商品名稱、價格與規格，先建立圖片庫存資料。","sku":"new-souvenir-image-02","temporaryPrice":true,"newArrival":true}');
INSERT OR IGNORE INTO product_images (product_id, image_key, sort_order, is_primary) SELECT id, 'images/S__294150148_0.jpg', 0, 1 FROM products WHERE slug = 'new-souvenir-image-02';
INSERT OR IGNORE INTO products (category_id, name, slug, description, price, stock, image_key, is_active, metadata_json)
VALUES ((SELECT id FROM categories WHERE slug = '伴手禮'), '伴手禮新品圖片 03', 'new-souvenir-image-03', '待補商品名稱、價格與規格，先建立圖片庫存資料。', 0, 0, 'images/S__294150149_0.jpg', 0, '{"priceValue":0,"day":5,"img":"/assets/images/S__294150149_0.jpg","desc":"待補商品名稱、價格與規格，先建立圖片庫存資料。","sku":"new-souvenir-image-03","temporaryPrice":true,"newArrival":true}');
INSERT OR IGNORE INTO product_images (product_id, image_key, sort_order, is_primary) SELECT id, 'images/S__294150149_0.jpg', 0, 1 FROM products WHERE slug = 'new-souvenir-image-03';
INSERT OR IGNORE INTO products (category_id, name, slug, description, price, stock, image_key, is_active, metadata_json)
VALUES ((SELECT id FROM categories WHERE slug = '伴手禮'), '伴手禮新品圖片 04', 'new-souvenir-image-04', '待補商品名稱、價格與規格，先建立圖片庫存資料。', 0, 0, 'images/S__294150150_0.jpg', 0, '{"priceValue":0,"day":5,"img":"/assets/images/S__294150150_0.jpg","desc":"待補商品名稱、價格與規格，先建立圖片庫存資料。","sku":"new-souvenir-image-04","temporaryPrice":true,"newArrival":true}');
INSERT OR IGNORE INTO product_images (product_id, image_key, sort_order, is_primary) SELECT id, 'images/S__294150150_0.jpg', 0, 1 FROM products WHERE slug = 'new-souvenir-image-04';
INSERT OR IGNORE INTO products (category_id, name, slug, description, price, stock, image_key, is_active, metadata_json)
VALUES ((SELECT id FROM categories WHERE slug = '伴手禮'), '伴手禮新品圖片 05', 'new-souvenir-image-05', '待補商品名稱、價格與規格，先建立圖片庫存資料。', 0, 0, 'images/S__294150152_0.jpg', 0, '{"priceValue":0,"day":5,"img":"/assets/images/S__294150152_0.jpg","desc":"待補商品名稱、價格與規格，先建立圖片庫存資料。","sku":"new-souvenir-image-05","temporaryPrice":true,"newArrival":true}');
INSERT OR IGNORE INTO product_images (product_id, image_key, sort_order, is_primary) SELECT id, 'images/S__294150152_0.jpg', 0, 1 FROM products WHERE slug = 'new-souvenir-image-05';
INSERT OR IGNORE INTO products (category_id, name, slug, description, price, stock, image_key, is_active, metadata_json)
VALUES ((SELECT id FROM categories WHERE slug = '伴手禮'), '伴手禮新品圖片 06', 'new-souvenir-image-06', '待補商品名稱、價格與規格，先建立圖片庫存資料。', 0, 0, 'images/S__294150153_0.jpg', 0, '{"priceValue":0,"day":5,"img":"/assets/images/S__294150153_0.jpg","desc":"待補商品名稱、價格與規格，先建立圖片庫存資料。","sku":"new-souvenir-image-06","temporaryPrice":true,"newArrival":true}');
INSERT OR IGNORE INTO product_images (product_id, image_key, sort_order, is_primary) SELECT id, 'images/S__294150153_0.jpg', 0, 1 FROM products WHERE slug = 'new-souvenir-image-06';
INSERT OR IGNORE INTO products (category_id, name, slug, description, price, stock, image_key, is_active, metadata_json)
VALUES ((SELECT id FROM categories WHERE slug = '伴手禮'), '伴手禮新品圖片 07', 'new-souvenir-image-07', '待補商品名稱、價格與規格，先建立圖片庫存資料。', 0, 0, 'images/S__294150154_0.jpg', 0, '{"priceValue":0,"day":5,"img":"/assets/images/S__294150154_0.jpg","desc":"待補商品名稱、價格與規格，先建立圖片庫存資料。","sku":"new-souvenir-image-07","temporaryPrice":true,"newArrival":true}');
INSERT OR IGNORE INTO product_images (product_id, image_key, sort_order, is_primary) SELECT id, 'images/S__294150154_0.jpg', 0, 1 FROM products WHERE slug = 'new-souvenir-image-07';
INSERT OR IGNORE INTO products (category_id, name, slug, description, price, stock, image_key, is_active, metadata_json)
VALUES ((SELECT id FROM categories WHERE slug = '伴手禮'), '伴手禮新品圖片 08', 'new-souvenir-image-08', '待補商品名稱、價格與規格，先建立圖片庫存資料。', 0, 0, 'images/S__294150155_0.jpg', 0, '{"priceValue":0,"day":5,"img":"/assets/images/S__294150155_0.jpg","desc":"待補商品名稱、價格與規格，先建立圖片庫存資料。","sku":"new-souvenir-image-08","temporaryPrice":true,"newArrival":true}');
INSERT OR IGNORE INTO product_images (product_id, image_key, sort_order, is_primary) SELECT id, 'images/S__294150155_0.jpg', 0, 1 FROM products WHERE slug = 'new-souvenir-image-08';
INSERT OR IGNORE INTO products (category_id, name, slug, description, price, stock, image_key, is_active, metadata_json)
VALUES ((SELECT id FROM categories WHERE slug = '伴手禮'), '伴手禮新品圖片 09', 'new-souvenir-image-09', '待補商品名稱、價格與規格，先建立圖片庫存資料。', 0, 0, 'images/S__294150156_0.jpg', 0, '{"priceValue":0,"day":5,"img":"/assets/images/S__294150156_0.jpg","desc":"待補商品名稱、價格與規格，先建立圖片庫存資料。","sku":"new-souvenir-image-09","temporaryPrice":true,"newArrival":true}');
INSERT OR IGNORE INTO product_images (product_id, image_key, sort_order, is_primary) SELECT id, 'images/S__294150156_0.jpg', 0, 1 FROM products WHERE slug = 'new-souvenir-image-09';
INSERT OR IGNORE INTO products (category_id, name, slug, description, price, stock, image_key, is_active, metadata_json)
VALUES ((SELECT id FROM categories WHERE slug = '伴手禮'), '伴手禮新品圖片 10', 'new-souvenir-image-10', '待補商品名稱、價格與規格，先建立圖片庫存資料。', 0, 0, 'images/S__294150157_0.jpg', 0, '{"priceValue":0,"day":5,"img":"/assets/images/S__294150157_0.jpg","desc":"待補商品名稱、價格與規格，先建立圖片庫存資料。","sku":"new-souvenir-image-10","temporaryPrice":true,"newArrival":true}');
INSERT OR IGNORE INTO product_images (product_id, image_key, sort_order, is_primary) SELECT id, 'images/S__294150157_0.jpg', 0, 1 FROM products WHERE slug = 'new-souvenir-image-10';
INSERT OR IGNORE INTO products (category_id, name, slug, description, price, stock, image_key, is_active, metadata_json)
VALUES ((SELECT id FROM categories WHERE slug = '伴手禮'), '伴手禮新品圖片 11', 'new-souvenir-image-11', '待補商品名稱、價格與規格，先建立圖片庫存資料。', 0, 0, 'images/S__294150158_0.jpg', 0, '{"priceValue":0,"day":5,"img":"/assets/images/S__294150158_0.jpg","desc":"待補商品名稱、價格與規格，先建立圖片庫存資料。","sku":"new-souvenir-image-11","temporaryPrice":true,"newArrival":true}');
INSERT OR IGNORE INTO product_images (product_id, image_key, sort_order, is_primary) SELECT id, 'images/S__294150158_0.jpg', 0, 1 FROM products WHERE slug = 'new-souvenir-image-11';

INSERT OR IGNORE INTO products (category_id, name, slug, description, price, stock, image_key, is_active, metadata_json)
VALUES ((SELECT id FROM categories WHERE slug = '生日蛋糕'), '生日蛋糕新品圖片 01', 'new-birthday-cake-image-01', '待補商品名稱、價格與規格，先建立圖片庫存資料。', 0, 0, 'images/S__294150160_0.jpg', 0, '{"priceValue":0,"day":7,"img":"/assets/images/S__294150160_0.jpg","desc":"待補商品名稱、價格與規格，先建立圖片庫存資料。","sku":"new-birthday-cake-image-01","temporaryPrice":true,"newArrival":true}');
INSERT OR IGNORE INTO product_images (product_id, image_key, sort_order, is_primary) SELECT id, 'images/S__294150160_0.jpg', 0, 1 FROM products WHERE slug = 'new-birthday-cake-image-01';
INSERT OR IGNORE INTO products (category_id, name, slug, description, price, stock, image_key, is_active, metadata_json)
VALUES ((SELECT id FROM categories WHERE slug = '生日蛋糕'), '生日蛋糕新品圖片 02', 'new-birthday-cake-image-02', '待補商品名稱、價格與規格，先建立圖片庫存資料。', 0, 0, 'images/S__294150161_0.jpg', 0, '{"priceValue":0,"day":7,"img":"/assets/images/S__294150161_0.jpg","desc":"待補商品名稱、價格與規格，先建立圖片庫存資料。","sku":"new-birthday-cake-image-02","temporaryPrice":true,"newArrival":true}');
INSERT OR IGNORE INTO product_images (product_id, image_key, sort_order, is_primary) SELECT id, 'images/S__294150161_0.jpg', 0, 1 FROM products WHERE slug = 'new-birthday-cake-image-02';
INSERT OR IGNORE INTO products (category_id, name, slug, description, price, stock, image_key, is_active, metadata_json)
VALUES ((SELECT id FROM categories WHERE slug = '生日蛋糕'), '生日蛋糕新品圖片 03', 'new-birthday-cake-image-03', '待補商品名稱、價格與規格，先建立圖片庫存資料。', 0, 0, 'images/S__294150162_0.jpg', 0, '{"priceValue":0,"day":7,"img":"/assets/images/S__294150162_0.jpg","desc":"待補商品名稱、價格與規格，先建立圖片庫存資料。","sku":"new-birthday-cake-image-03","temporaryPrice":true,"newArrival":true}');
INSERT OR IGNORE INTO product_images (product_id, image_key, sort_order, is_primary) SELECT id, 'images/S__294150162_0.jpg', 0, 1 FROM products WHERE slug = 'new-birthday-cake-image-03';
INSERT OR IGNORE INTO products (category_id, name, slug, description, price, stock, image_key, is_active, metadata_json)
VALUES ((SELECT id FROM categories WHERE slug = '生日蛋糕'), '生日蛋糕新品圖片 04', 'new-birthday-cake-image-04', '待補商品名稱、價格與規格，先建立圖片庫存資料。', 0, 0, 'images/S__294150163_0.jpg', 0, '{"priceValue":0,"day":7,"img":"/assets/images/S__294150163_0.jpg","desc":"待補商品名稱、價格與規格，先建立圖片庫存資料。","sku":"new-birthday-cake-image-04","temporaryPrice":true,"newArrival":true}');
INSERT OR IGNORE INTO product_images (product_id, image_key, sort_order, is_primary) SELECT id, 'images/S__294150163_0.jpg', 0, 1 FROM products WHERE slug = 'new-birthday-cake-image-04';
INSERT OR IGNORE INTO products (category_id, name, slug, description, price, stock, image_key, is_active, metadata_json)
VALUES ((SELECT id FROM categories WHERE slug = '生日蛋糕'), '生日蛋糕新品圖片 05', 'new-birthday-cake-image-05', '待補商品名稱、價格與規格，先建立圖片庫存資料。', 0, 0, 'images/S__294150164_0.jpg', 0, '{"priceValue":0,"day":7,"img":"/assets/images/S__294150164_0.jpg","desc":"待補商品名稱、價格與規格，先建立圖片庫存資料。","sku":"new-birthday-cake-image-05","temporaryPrice":true,"newArrival":true}');
INSERT OR IGNORE INTO product_images (product_id, image_key, sort_order, is_primary) SELECT id, 'images/S__294150164_0.jpg', 0, 1 FROM products WHERE slug = 'new-birthday-cake-image-05';
INSERT OR IGNORE INTO products (category_id, name, slug, description, price, stock, image_key, is_active, metadata_json)
VALUES ((SELECT id FROM categories WHERE slug = '生日蛋糕'), '生日蛋糕新品圖片 06', 'new-birthday-cake-image-06', '待補商品名稱、價格與規格，先建立圖片庫存資料。', 0, 0, 'images/S__294150165_0.jpg', 0, '{"priceValue":0,"day":7,"img":"/assets/images/S__294150165_0.jpg","desc":"待補商品名稱、價格與規格，先建立圖片庫存資料。","sku":"new-birthday-cake-image-06","temporaryPrice":true,"newArrival":true}');
INSERT OR IGNORE INTO product_images (product_id, image_key, sort_order, is_primary) SELECT id, 'images/S__294150165_0.jpg', 0, 1 FROM products WHERE slug = 'new-birthday-cake-image-06';
INSERT OR IGNORE INTO products (category_id, name, slug, description, price, stock, image_key, is_active, metadata_json)
VALUES ((SELECT id FROM categories WHERE slug = '生日蛋糕'), '生日蛋糕新品圖片 07', 'new-birthday-cake-image-07', '待補商品名稱、價格與規格，先建立圖片庫存資料。', 0, 0, 'images/S__294150166_0.jpg', 0, '{"priceValue":0,"day":7,"img":"/assets/images/S__294150166_0.jpg","desc":"待補商品名稱、價格與規格，先建立圖片庫存資料。","sku":"new-birthday-cake-image-07","temporaryPrice":true,"newArrival":true}');
INSERT OR IGNORE INTO product_images (product_id, image_key, sort_order, is_primary) SELECT id, 'images/S__294150166_0.jpg', 0, 1 FROM products WHERE slug = 'new-birthday-cake-image-07';
